---
title: "Ford Tweet"
author: "Manuel Perez"
date: "October 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(syuzhet)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(stringr)
library(readr)
```

```{r}
### Ford Tweet on September 9, 2018
Ford_9_9_18 <- " “Ford has abruptly killed a plan to sell a Chinese-made small vehicle in the U.S. because of the prospect of higher U.S. Tariffs.” CNBC. This is just the beginning. This car can now be BUILT IN THE U.S.A. and Ford will pay no tariffs!"
```

```{r}
### Ford Tweet on March 28, 2017
Ford_3_28_17 <- "Big announcement by Ford today. Major investment to be made in three Michigan plants. Car companies coming back to U.S. JOBS! JOBS! JOBS!"
```

```{r}
### Ford Tweet on January 24, 2017
Ford_1_24_17 <- "Great meeting with Ford CEO Mark Fields and General Motors CEO Mary Barra at the @WhiteHouse today."
```

```{r}
### Ford Tweet on January 9, 2017
Ford_1_9_17 <- "Ford said last week that it will expand in Michigan and U.S. instead of building a BILLION dollar plant in Mexico. Thank you Ford & Fiat C!"
```

```{r}
### Ford Tweet on January 4, 2017
Ford_1_4_17 <- "Thank you to Ford for scrapping a new plant in Mexico and creating 700 new jobs in the U.S. This is just the beginning - much more to follow"
```

```{r}
### Ford Tweet on July 14, 2015
Ford_7_14_15 <- "Ford is MOVING jobs from Michigan to Mexico AGAIN! As President, this will stop on Day One! Jobs will stay here."
```

```{r}
### Breaks up into sentences
Ford_9_9_18_sentences <- get_sentences(Ford_9_9_18)
Ford_3_28_17_sentences <- get_sentences(Ford_3_28_17)
Ford_1_24_17_sentences <- get_sentences(Ford_1_24_17)
Ford_1_9_17_sentences <- get_sentences(Ford_1_9_17)
Ford_1_4_17_sentences <- get_sentences(Ford_1_4_17)
Ford_7_14_15_sentences <- get_sentences(Ford_7_14_15)
```

```{r}
###If want tweet as tokens (words)
Ford_9_9_18_words <- get_tokens(Ford_9_9_18, pattern = "\\W")
Ford_3_28_17_words <- get_tokens(Ford_3_28_17, pattern = "\\W")
Ford_1_24_17_words <- get_tokens(Ford_1_24_17, pattern = "\\W")
Ford_1_9_17_words <- get_tokens(Ford_1_9_17, pattern = "\\W")
Ford_1_4_17_words <- get_tokens(Ford_1_4_17, pattern = "\\W")
Ford_7_14_15_words <- get_tokens(Ford_7_14_15, pattern = "\\W")
```


```{r}
### Sentiment of Ford tweet as sentences
Ford_9_9_18_ments <- get_sentiment(Ford_9_9_18_sentences, method="afinn")
Ford_3_28_17_ments <- get_sentiment(Ford_3_28_17_sentences, method="afinn")
Ford_1_24_17_ments <- get_sentiment(Ford_1_24_17_sentences, method="afinn")
Ford_1_9_17_ments <- get_sentiment(Ford_1_9_17_sentences, method="afinn")
Ford_1_4_17_ments <- get_sentiment(Ford_1_4_17_sentences, method="afinn")
Ford_7_14_15_ments <- get_sentiment(Ford_7_14_15_sentences, method="afinn")
```

```{r}
### Sentiment of Ford tweet as words
Ford_9_9_18_mentw <- get_sentiment(Ford_9_9_18_words, method="afinn")
Ford_3_28_17_mentw <- get_sentiment(Ford_3_28_17_words, method="afinn")
Ford_1_24_17_mentw <- get_sentiment(Ford_1_24_17_words, method="afinn")
Ford_1_9_17_mentw <- get_sentiment(Ford_1_9_17_words, method="afinn")
Ford_1_4_17_mentw <- get_sentiment(Ford_1_4_17_words, method="afinn")
Ford_7_14_15_mentw <- get_sentiment(Ford_7_14_15_words, method="afinn")
```

```{r}
### Sentiment analysis of Ford tweet as sentences
Ford_9_9_18_ments
Ford_3_28_17_ments
Ford_1_24_17_ments
Ford_1_9_17_ments
Ford_1_4_17_ments
Ford_7_14_15_ments
```

```{r}
### Sentiment analysis of Ford tweet as words
Ford_9_9_18_mentw
Ford_3_28_17_mentw
Ford_1_24_17_mentw
Ford_1_9_17_mentw
Ford_1_4_17_mentw
Ford_7_14_15_mentw
```

```{r}
### Summation of Sentiment analysis of Ford tweet as sentences
sum(Ford_9_9_18_ments) 
sum(Ford_3_28_17_ments)
sum(Ford_1_24_17_ments)
sum(Ford_1_9_17_ments)
sum(Ford_1_4_17_ments)
sum(Ford_7_14_15_ments)

#Mean
mean(Ford_9_9_18_ments) 
mean(Ford_3_28_17_ments)
mean(Ford_1_24_17_ments)
mean(Ford_1_9_17_ments)
mean(Ford_1_4_17_ments)
mean(Ford_7_14_15_ments)
```

```{r}
### Summation of Sentiment analysis of Ford tweet as words
sum(Ford_9_9_18_mentw) 
sum(Ford_3_28_17_mentw)
sum(Ford_1_24_17_mentw)
sum(Ford_1_9_17_mentw)
sum(Ford_1_4_17_mentw)
sum(Ford_7_14_15_mentw)

#Mean
mean(Ford_9_9_18_mentw) 
mean(Ford_3_28_17_mentw)
mean(Ford_1_24_17_mentw)
mean(Ford_1_9_17_mentw)
mean(Ford_1_4_17_mentw)
mean(Ford_7_14_15_mentw)
```

```{r}
### Summary of sentiment analysis of Ford tweet as sentences
summary(Ford_9_9_18_ments)
summary(Ford_3_28_17_ments)
summary(Ford_1_24_17_ments)
summary(Ford_1_9_17_ments)
summary(Ford_1_4_17_ments)
summary(Ford_7_14_15_ments)
```

```{r}
### Summary of sentiment analysis of Ford tweet as words
summary(Ford_9_9_18_mentw)
summary(Ford_3_28_17_mentw)
summary(Ford_1_24_17_mentw)
summary(Ford_1_9_17_mentw)
summary(Ford_1_4_17_mentw)
summary(Ford_7_14_15_mentw)
```

